# Generated by Django 4.1.2 on 2023-03-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("store_name", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
