# Generated by Django 4.1.2 on 2023-03-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restapp", "0002_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
