# Generated by Django 4.1.7 on 2023-03-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_store_store_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
    ]
