# Generated by Django 4.1.7 on 2023-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0004_user_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(default='', max_length=255)),
                ('product_name', models.CharField(default='', max_length=255)),
                ('influencer_name', models.CharField(default='', max_length=255)),
                ('coupon', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
